"""
mkmdf.py - Scrive il file di definizione del monitor (MDF) dell'emulatore.

    python tools/mkmdf.py [uscita]     (predefinita: tools/dist/HostFS/Monitors/ArchieEmu,fff)

Dalla 3.5 il Display Manager costruisce i menu dei colori e delle
risoluzioni dall'elenco dei modi di un MDF, caricato con *LoadModeFile
(di solito da !Boot): senza, ogni scelta da' "The Display Manager does not
support that combination of colours and resolution". Con un MDF caricato il
kernel accetta pero' solo le risoluzioni che l'MDF elenca, anche per i modi
numerati: per questo ci sono tutte quelle classiche (320x256, 640x256,
1056x256, 640x512...) a 50 Hz come sulla TV, senza nome (mode_name vuoto: non
compaiono nel menu), piu' i modi VESA a 60 Hz col nome. La frequenza dei
quadri conta: e' quella che i giochi vedono.

Formato: h_timings = sincronismo, portico posteriore, bordo sinistro,
immagine, bordo destro, portico anteriore (in pixel); v_timings uguale in
righe; pixel_rate in kHz; sync_pol bit 0 = orizzontale negativo, bit 1 =
verticale negativo.
"""
import os
import sys

TV_H = {  # larghezza: (pixel_rate kHz, h_timings) a 15,625 kHz (64 us per riga)
    160: (4000, (18, 15, 22, 160, 22, 19)),
    320: (8000, (36, 31, 44, 320, 44, 37)),
    640: (16000, (72, 62, 88, 640, 88, 74)),
    768: (16000, (72, 62, 30, 768, 30, 62)),
    1056: (24000, (108, 94, 90, 1056, 90, 98)),
}
TV_V = {  # altezza: v_timings su 312 righe (50 Hz)
    200: (3, 30, 26, 200, 26, 27),
    250: (3, 19, 17, 250, 17, 6),
    256: (3, 16, 17, 256, 17, 3),
    288: (3, 16, 2, 288, 2, 1),
}

modes = []
for w, (rate, h) in TV_H.items():
    for hh, v in TV_V.items():
        modes.append(("", w, hh, rate, h, v, 0))


def vesa(name, h, v, hz, pol):
    rate = round(sum(h) * sum(v) * hz / 1000)
    modes.append((name, h[3], v[3], rate, h, v, pol))


V480 = (2, 33, 0, 480, 0, 10)                      # 525 righe
V352 = (2, 46, 0, 352, 0, 40)                      # 440 righe
vesa("640 x 480", (96, 48, 0, 640, 0, 16), V480, 59.94, 3)
vesa("", (48, 24, 0, 360, 0, 18), V480, 60, 3)     # modo 47
vesa("", (48, 24, 0, 320, 0, 8), V480, 60, 3)      # modi 48-49
vesa("", (96, 112, 0, 896, 0, 48), V352, 60, 3)    # modi 37-40
vesa("", (96, 48, 0, 640, 0, 16), V352, 60, 3)     # modi 41-43
vesa("640 x 512", (64, 96, 0, 640, 0, 32), (3, 15, 0, 512, 0, 2), 60, 3)
vesa("800 x 600", (128, 88, 0, 800, 0, 40), (4, 23, 0, 600, 0, 1), 60.32, 0)
vesa("1024 x 768", (136, 160, 0, 1024, 0, 24), (6, 29, 0, 768, 0, 3), 60, 3)
vesa("", (112, 144, 0, 1152, 0, 64), (3, 30, 0, 896, 0, 3), 60, 3)   # modo 23
vesa("1280 x 1024", (112, 248, 0, 1280, 0, 48), (3, 38, 0, 1024, 0, 1), 60.02, 0)

out = ["# Monitor definition file for ArchieEmu's Risc PC (RISC OS 3.5-3.7),",
       "# loaded by !Boot. Classic Acorn resolutions at TV rates (50 Hz, unnamed:",
       "# they keep the numbered modes working) and named VESA modes at 60 Hz.",
       "# Generated by tools/mkmdf.py.",
       "file_format:1", "monitor_title:ArchieEmu", "DPMS_state:0", ""]
for name, w, hh, rate, h, v, pol in modes:
    out += ["startmode", "mode_name:" + name, "x_res:%d" % w, "y_res:%d" % hh,
            "pixel_rate:%d" % rate, "h_timings:" + ",".join(map(str, h)),
            "v_timings:" + ",".join(map(str, v)), "sync_pol:%d" % pol, "endmode", ""]

path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "dist", "HostFS", "Monitors", "ArchieEmu,fff")
with open(path, "w", newline="\n") as f:
    f.write("\n".join(out))
for name, w, hh, rate, h, v, pol in modes:
    print("%4dx%-4d %6d kHz  %5.2f Hz  %s" % (w, hh, rate, rate * 1000 / sum(h) / sum(v), name))
